_: {
  imports = [
    ./minimal.nix
    ./benchmarks.nix
    ./caelestia.nix
    ./caelestia-theme.nix
    ./clipboard.nix
    ./codedb.nix
    ./cursor.nix
    ./direnv.nix
    ./dotfiles.nix
    ./file-management.nix
    ./git.nix
    ./gpg-preset.nix
    ./gtk.nix
    ./hypr.nix
    ./mise.nix
    ./packages.nix
    ./passmenu.nix
    ./qt.nix
    ./readline.nix
    ./rtk.nix
    ./secret-service.nix
    ./skills-sync.nix
    ./treehouse-prune.nix
    ./wezterm.nix
    ./unity.nix
    ./zen.nix
    ./zen-profile-sync.nix
  ];
}
