general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    color = rgb(32, 31, 35)
}

input-field {
    monitor =
    size = 240, 52
    position = 0, -80
    dots_center = true
    fade_on_empty = false
    inner_color = rgb(45, 44, 50)
    outer_color = rgb(194, 193, 255)
    outline_thickness = 2
    placeholder_text = Password...
    font_color = rgb(229, 225, 231)
}
