name: Build and check

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".gitignore"
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".gitignore"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: atqamz-universe
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: flake check
        run: nix flake check --print-build-logs
